import React from 'react';
import { Table } from 'semantic-ui-react';
import PasivoEntryInput from './PasivoEntryInput';


// This table is done with hard coded values because those values are never going to change.
// Ok, I should have mapped this, but I have a excuse: the table was 1/4 when I started it and
// the way Semantic UI 'structured' table work wasn't clear when starting
const PasivoEntryTableEventuales = (props) => {
  return (
    <Table textAlign="center" celled structured>
      <Table.Header>
        <Table.Row>
          <Table.HeaderCell>Rama</Table.HeaderCell>
          <Table.HeaderCell>Subdivision</Table.HeaderCell>
          <Table.HeaderCell>Costo</Table.HeaderCell>
          <Table.HeaderCell>Cuenta Contable</Table.HeaderCell>
          <Table.HeaderCell>Cuota</Table.HeaderCell>
          <Table.HeaderCell>Provision</Table.HeaderCell>
          <Table.HeaderCell>Liquidacion</Table.HeaderCell>
          <Table.HeaderCell>Diferencia</Table.HeaderCell>
        </Table.Row>
      </Table.Header>

      <Table.Body>
        <Table.Row>
          <Table.Cell rowSpan="9">Enfermedad y Maternidad</Table.Cell>
          <Table.Cell rowSpan="5">Patronal</Table.Cell>
          <Table.Cell rowSpan="5">99</Table.Cell>
          <Table.Cell rowSpan="5">452210</Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Cuota Fija</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="cuotaFija"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="cuotaFija"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="cuotaFija"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Exc. Patronal</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excPatronal"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excPatronal"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excPatronal"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>P.D. Patronal</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdPatronal"
            />
          </Table.Cell>         
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdPatronal"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdPatronal"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>G.M.P. Patronal</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpPatronal"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpPatronal"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpPatronal"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell rowSpan="4">Obrera</Table.Cell>
          <Table.Cell rowSpan="4">9U</Table.Cell>
          <Table.Cell rowSpan="4">452211</Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Exc. Obrera</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="excObrera"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>P.D. Obrera</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="pdObrera"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>G.M.P. Obrera</Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpObrera"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpObrera"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gmpObrera"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell rowSpan="2">Invalidez y Vida</Table.Cell>
          <Table.Cell>Patronal</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivPatronal"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivPatronal"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivPatronal"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Obrera</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivObrera"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="ivObrera"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Riesgo de Trabajo</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>99</Table.Cell>
          <Table.Cell>452020</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="riesgoTrabajo"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="riesgoTrabajo"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="riesgoTrabajo"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Guarderia y Pres Soc</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>99</Table.Cell>
          <Table.Cell>452030</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gps"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gps"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="gps"
            />
          </Table.Cell>     
        </Table.Row>
        {props.metadata.modo === 'Pasivo' || (props.metadata.mes % 2) === 0 ?
        <React.Fragment>
        <Table.Row>
          <Table.Cell>Retiro</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>95</Table.Cell>
          <Table.Cell>409518</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="95"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="95"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="95"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell rowSpan="2">Cesantia y Vejez</Table.Cell>
          <Table.Cell>Patronal</Table.Cell>
          <Table.Cell>9E</Table.Cell>
          <Table.Cell>451450</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9E"
            />
          </Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9E"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9E"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>Obrera</Table.Cell>
          <Table.Cell>9Q</Table.Cell>
          <Table.Cell>451451</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9Q"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9Q"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="9Q"
            />
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>INFONAVIT</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>2X</Table.Cell>
          <Table.Cell>451140</Table.Cell>
          <Table.Cell></Table.Cell>
          <Table.Cell>
            <PasivoEntryInput
              type="provision"
              shouldBeDisabled={props.provisionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="2X"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="liquidacion"
              shouldBeDisabled={props.liquidacionShouldBeDisabled}
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="2X"
            />
          </Table.Cell>          
          <Table.Cell>
            <PasivoEntryInput
              type="diferencia"
              shouldBeDisabled
              inputData={props.inputData}
              provisionData={props.provisionData}
              diferenciaData={props.diferenciaData}
              onChange={props.inputHandleChange}
              onBlur={props.inputHandleBlur}
              name="2X"
            />
          </Table.Cell>
        </Table.Row>
        </React.Fragment>
        : null }
      </Table.Body>
    </Table>
  );
};

export default PasivoEntryTableEventuales;
